// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.apress.prospring3.ch20.domain;

import com.apress.prospring3.ch20.domain.Contact;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Contact_Roo_Configurable {
    
    declare @type: Contact: @Configurable;
    
}
